---
title: "Data"
output: html_document
---
For this project, we downloaded three different datasets to answer specific research questions.

### 1. Historical Fluid Beverage Milk Sales Quantities by Product Data
This dataset was downloaded from the [U.S. Department of Agriculture](https://www.ers.usda.gov/data-products/dairy-data/). The variables in this dataset are:

- `year`: 1970-2023  
- `whole`: Whole milk sales  
- `2%-reduced-fat`: 2% reduced-fat milk sales  
- `1%-reduced-fat`: 1% reduced-fat milk sales  
- `skim`: Skim milk sales  
- `flavored-whole`: Flavored whole milk sales  
- `flavored-other-than-whole`: Flavored non-whole milk sales  


### 2. Historical Milk Cows and Milk Production Data by State and Region

This dataset was downloaded from the [U.S. Department of Agriculture](https://www.ers.usda.gov/data-products/dairy-data/). The variables in this dataset are: 

- `region`: U.S. regions
- `state`: U.S. states
- `year`: Year (1970-2023)
- `milk_cows`: Number of milk cows (in thousands)
- `milk_production`: Milk production (in million pounds)

### 3. Nutrional Data
The data for our nutritional analysis was found in four separate Excel files. We compiled these files into one sheet and then created a new, cleaner Excel sheet for analysis. The data pertains to the nutritional information of Cream-O-Land Dairy (a producer of milk). This information was compared to other brands, but the differences were marginal enough to be considered negligible for our analysis.
